/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rdujusymvebxndykyvhu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkdWp1c3ltdmVieG5keWt5dmh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NTQyNjEsImV4cCI6MjA3MzEzMDI2MX0.2koadjTydnQREvtl6kyAmmmCJ2sBksatwNICSdoeIUg"

// Derived exports that are commonly needed
export const supabaseUrl = `https://${projectId}.supabase.co`
export const apiBaseUrl = `https://${projectId}.supabase.co/functions/v1/make-server-e547215c`